version: "3.8"

networks:
  portal-network:
    driver: bridge

services:
  portal-frontend:
    build: ./frontend
    environment:
      - DATABASE_URL="postgres://postgres:password@localhost:5432/portal-db"
      - DATABASE_NAME="portal-db"
      - DATABASE_PASSWORD="password"
      - DATABASE_USER="postgres"
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
    networks:
      - portal-network

  portal-data-service:
    build: ./backend/data-service
    ports:
      - "3102:3102"
    environment:
      - DATABASE_URL="postgres://postgres:password@localhost:5432/portal-db"
      - DATABASE_NAME="portal-db"
      - DATABASE_PASSWORD="password"
      - DATABASE_USER="postgres"
    volumes:
      - ./backend/data-service:/app/data-service
    working_dir: /app/data-service
    networks:
      - portal-network

  portal-db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=portal-db
    ports:
      - "5432:5432"
    networks:
      - portal-network