version: "3.8"


services:
  portal-frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    working_dir: /app/frontend
  portal-data-service:
    build: ./backend/data-service
    ports:
      - "3102:3102"
    volumes:
      - ./backend/data-service:/app/data-service
    working_dir: /app/data-service