name: Trigger auto deployment for portfolio-portal-data-service

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'backend/data-service/**'
    - '.github/workflows/portfolio-portal-data-service-AutoDeployTrigger-fdfa6e55-228e-4218-878c-c1c99a570d37.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.PORTFOLIOPORTALDATASERVICE_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend/data-service 
          registryUrl: docker.io
          registryUsername: ${{ secrets.PORTFOLIOPORTALDATASERVICE_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PORTFOLIOPORTALDATASERVICE_REGISTRY_PASSWORD }}
          containerAppName: portfolio-portal-data-service
          resourceGroup: portfolioPortalRG
          imageToBuild: warbuckle117/portfolio-portal-data-service:${{ github.sha }}
          dockerfilePath: Dockerfile

     

